/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#362e38",
        "on-tertiary-fixed-variant": "#005237",
        "surface-dim": "#e3d6e4",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#ba94bc",
        "secondary-container": "#fecd79",
        "primary-container": "#4a2c4e",
        "background": "#fff7fc",
        "tertiary-container": "#00402a",
        "tertiary": "#002819",
        "surface-variant": "#ecdeed",
        "on-surface-variant": "#4c444c",
        "on-tertiary-fixed": "#002114",
        "primary-fixed-dim": "#e2b9e4",
        "on-background": "#201923",
        "secondary-fixed-dim": "#efbf6c",
        "secondary-fixed": "#ffdea9",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#a8f2cc",
        "surface-container-high": "#f2e4f2",
        "primary-fixed": "#ffd6ff",
        "error": "#ba1a1a",
        "surface": "#fff7fc",
        "on-primary-fixed": "#2c1031",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#5b3c5f",
        "on-secondary-container": "#785508",
        "inverse-primary": "#e2b9e4",
        "inverse-on-surface": "#faecfb",
        "on-primary": "#ffffff",
        "surface-container": "#f7eaf8",
        "primary": "#331737",
        "on-surface": "#201923",
        "surface-container-low": "#fdeffe",
        "on-secondary": "#ffffff",
        "secondary": "#7b580c",
        "on-secondary-fixed": "#271900",
        "outline-variant": "#cfc3cc",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#5f4100",
        "on-tertiary-container": "#66af8c",
        "surface-tint": "#745377",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#8cd6b1",
        "surface-bright": "#fff7fc",
        "surface-container-highest": "#ecdeed",
        "outline": "#7e747c",
        ayur: {
          bg: '#fff7fc',
          surface: '#fff7fc',
          soft: '#f7eaf8',
          mutedSurf: '#ecdeed',
          indigo: '#331737',
          indigoContainer: '#4a2c4e',
          rust: '#ba1a1a',
          rustTint: '#ffdad6',
          text: '#201923',
          muted: '#4c444c',
          hairline: '#cfc3cc',
          success: '#005237',
          brass: '#7b580c',
        }
      },
      fontFamily: {
        sans: ['Mukta', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'monospace'],
      }
    }
  },
  plugins: [],
}
